[build]
  command = "npm install && npm run build --workspace=@commitlol/engine && npm run build --workspace=web"
  publish = "apps/web/.next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
